// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXeviL95zQRYtG_fkBGdV-tS-gLMM8n2g',
    appId: '1:730233418308:web:6d85ca3c484600778f8211',
    messagingSenderId: '730233418308',
    projectId: 'we-chat-e4cd6',
    authDomain: 'we-chat-e4cd6.firebaseapp.com',
    storageBucket: 'we-chat-e4cd6.appspot.com',
    measurementId: 'G-DZSE7SBKKS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_e6-NvUypiFH5-G__zG1gYcqr5kLFzSM',
    appId: '1:730233418308:android:d73a4c45a92ec4c28f8211',
    messagingSenderId: '730233418308',
    projectId: 'we-chat-e4cd6',
    storageBucket: 'we-chat-e4cd6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByqULRGMeZLuRwZgD01F0br3bUNZ3BzFE',
    appId: '1:730233418308:ios:3e639b514606757a8f8211',
    messagingSenderId: '730233418308',
    projectId: 'we-chat-e4cd6',
    storageBucket: 'we-chat-e4cd6.appspot.com',
    iosBundleId: 'com.example.weChat',
  );
}
